[project]
name = "gimbal"
version = "0.1.0"
description = "GUI wrapper for Claude Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.22.0",
    "mcp-server-fetch>=2025.4.7",
    "pyinstaller>=6.17.0",
]
